name: Finalize Classes

on: [pull_request, push]

jobs:
    finalize_classes:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                php_version: ['7.3', '7.4', '8.0']

        name: "PHP ${{ matrix.php_version }}"

        steps:
            -   uses: actions/checkout@v2

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php_version }}
                    coverage: none

            -   run: |
                    mkdir standalone
                    cd standalone
                    # wait for deploy to packagist
                    sleep 60

            -   run: |
                    cd standalone
                    # run
                    composer require ssch/typo3-rector-prefixed:dev-master --dev --ansi
                    composer require doctrine/orm

            -
                run: |
                    cd standalone
                    vendor/bin/typo3-rector process ../tests/fixture-finalize --config ../ci/rector-finalize.php --ansi
