<T3DataStructure>
    <sheets>
        <sDEF>
            <ROOT>
                <TCEforms>
                    <sheetTitle>sheetTitle</sheetTitle>
                </TCEforms>
                <type>array</type>
                <el>
                    <settings.selectField>
                        <TCEforms>
                            <label>Select Field</label>
                            <config>
                                <type>select</type>
                                <renderType>selectSingle</renderType>
                                <items>
                                    <numIndex index="0" type="array">
                                        <numIndex index="0">Label</numIndex>
                                        <numIndex index="1"/>
                                    </numIndex>
                                    <numIndex index="1">
                                        <numIndex index="0">Label 1</numIndex>
                                        <numIndex index="1">1</numIndex>
                                    </numIndex>
                                    <numIndex index="2">
                                        <numIndex index="0">Label 2</numIndex>
                                        <numIndex index="1">2</numIndex>
                                    </numIndex>
                                </items>
                            </config>
                        </TCEforms>
                    </settings.selectField>
                </el>
            </ROOT>
        </sDEF>
    </sheets>
</T3DataStructure>
