<?php

use TYPO3\CMS\Extbase\Utility\ExtensionUtility;

ExtensionUtility::registerPlugin(
    'TYPO3.CMS.Form',
    'Formframework',
    'Form',
    'content-form'
);

ExtensionUtility::registerPlugin(
    'Form',
    'Formframework',
    'Form',
    'content-form'
);

?>
-----
<?php

use TYPO3\CMS\Extbase\Utility\ExtensionUtility;

ExtensionUtility::registerPlugin(
    'Form',
    'Formframework',
    'Form',
    'content-form'
);

ExtensionUtility::registerPlugin(
    'Form',
    'Formframework',
    'Form',
    'content-form'
);

?>
