<?php

$urlGeneral = TYPO3_URL_GENERAL;
$urlLicense = TYPO3_URL_LICENSE;
$urlException = TYPO3_URL_EXCEPTION;
$urlDonate = TYPO3_URL_DONATE;
$urlOpcache = TYPO3_URL_WIKI_OPCODECACHE;

?>
-----
<?php

use TYPO3\CMS\Core\Information\Typo3Information;
$urlGeneral = Typo3Information::TYPO3_URL_GENERAL;
$urlLicense = Typo3Information::TYPO3_URL_LICENSE;
$urlException = Typo3Information::TYPO3_URL_EXCEPTION;
$urlDonate = Typo3Information::TYPO3_URL_DONATE;
$urlOpcache = Typo3Information::TYPO3_URL_WIKI_OPCODECACHE;

?>
