<f:link.page addQueryString="1" noCacheHash="1">Link</f:link.page>
<f:link.page addQueryString="1"
    noCacheHash="1"
>Link</f:link.page>
<f:link.page noCacheHash="0">Link</f:link.page>
<f:link.typolink useCacheHash="1">Link</f:link.typolink>
<f:link.typolink useCacheHash="0">Link</f:link.typolink>
<f:uri.typolink parameter="{link}" additionalParams="&u=b" useCacheHash="true" />
-----
<f:link.page addQueryString="1">Link</f:link.page>
<f:link.page addQueryString="1"
   
>Link</f:link.page>
<f:link.page>Link</f:link.page>
<f:link.typolink>Link</f:link.typolink>
<f:link.typolink>Link</f:link.typolink>
<f:uri.typolink parameter="{link}" additionalParams="&u=b" />
