<?php

$database = TYPO3_db;
$username = TYPO3_db_username;
$password = TYPO3_db_password;
$host = TYPO3_db_host;

?>
-----
<?php

$database = $GLOBALS['TYPO3_CONF_VARS']['DB']['Connections']['Default']['dbname'];
$username = $GLOBALS['TYPO3_CONF_VARS']['DB']['Connections']['Default']['user'];
$password = $GLOBALS['TYPO3_CONF_VARS']['DB']['Connections']['Default']['password'];
$host = $GLOBALS['TYPO3_CONF_VARS']['DB']['Connections']['Default']['host'];

?>
