{v:uri.image(src:image.uid, treatIdAsReference: 1)}
{v:uri.image(src:image.uid, treatIdAsReference: 1, relative: 1)}
{v:uri.image(src:image.uid, treatIdAsReference: 1, relative: 0)}
{v:uri.image(src:image.uid, treatIdAsReference: 1, maxW: 250, maxH: 250)}
-----
{f:uri.image(src:image.uid, treatIdAsReference: 1)}
{f:uri.image(src:image.uid, treatIdAsReference: 1)}
{f:uri.image(src:image.uid, treatIdAsReference: 1, absolute: 1)}
{f:uri.image(src:image.uid, treatIdAsReference: 1, maxWidth: 250, maxHeight: 250)}
