services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TYPO3\CMS\T3editor\:
    resource: '../Classes/*'

  TYPO3\CMS\T3editor\EventListener\InitializeT3editorInEditFileForm:
    tags:
      - name: event.listener
        identifier: 'typo3-t3editor/initialize-t3editor-in-edit-file-form'

  TYPO3\CMS\T3editor\Controller\CodeCompletionController:
    tags: ['backend.controller']
