<?php

$var1 = TYPO3_URL_MAILINGLISTS;
$var2 = TYPO3_URL_DOCUMENTATION;
$var3 = TYPO3_URL_DOCUMENTATION_TSREF;
$var4 = TYPO3_URL_DOCUMENTATION_TSCONFIG;
$var5 = TYPO3_URL_CONSULTANCY;
$var6 = TYPO3_URL_CONTRIBUTE;
$var7 = TYPO3_URL_SECURITY;
$var8 = TYPO3_URL_DOWNLOAD;
$var9 = TYPO3_URL_SYSTEMREQUIREMENTS;
$nul = NUL;
$tab = TAB;
$sub = SUB;

$var10 = T3_ERR_SV_GENERAL;
$var11 = T3_ERR_SV_NOT_AVAIL;
$var12 = T3_ERR_SV_WRONG_SUBTYPE;
$var13 = T3_ERR_SV_NO_INPUT;
$var14 = T3_ERR_SV_FILE_NOT_FOUND;
$var15 = T3_ERR_SV_FILE_READ;
$var16 = T3_ERR_SV_FILE_WRITE;
$var17 = T3_ERR_SV_PROG_NOT_FOUND;
$var18 = T3_ERR_SV_PROG_FAILED;

?>
-----
<?php

use TYPO3\CMS\Core\Service\AbstractService;
$var1 = 'http://lists.typo3.org/cgi-bin/mailman/listinfo';
$var2 = 'https://typo3.org/documentation/';
$var3 = 'https://docs.typo3.org/typo3cms/TyposcriptReference/';
$var4 = 'https://docs.typo3.org/typo3cms/TSconfigReference/';
$var5 = 'https://typo3.org/support/professional-services/';
$var6 = 'https://typo3.org/contribute/';
$var7 = 'https://typo3.org/teams/security/';
$var8 = 'https://typo3.org/download/';
$var9 = 'https://typo3.org/typo3-cms/overview/requirements/';
$nul = "\x00";
$tab = "\t";
$sub = chr(26);

$var10 = AbstractService::ERROR_GENERAL;
$var11 = AbstractService::ERROR_SERVICE_NOT_AVAILABLE;
$var12 = AbstractService::ERROR_WRONG_SUBTYPE;
$var13 = AbstractService::ERROR_NO_INPUT;
$var14 = AbstractService::ERROR_FILE_NOT_FOUND;
$var15 = AbstractService::ERROR_FILE_NOT_READABLE;
$var16 = AbstractService::ERROR_FILE_NOT_WRITEABLE;
$var17 = AbstractService::ERROR_PROGRAM_NOT_FOUND;
$var18 = AbstractService::ERROR_PROGRAM_FAILED;

?>
