services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TYPO3\CMS\Tstemplate\:
    resource: '../Classes/*'

  TYPO3\CMS\Tstemplate\Hooks\DataHandlerClearCachePostProcHook:
    public: true
