<T3DataStructure>
    <sheets>
        <sDEF>
            <ROOT>
                <sheetTitle>
                    LLL:EXT:news/Resources/Private/Language/locallang_be.xlf:flexforms_tab.settings
                </sheetTitle>
                <type>array</type>
                <el>
                    <settings.topNewsRestriction>
                        <label>
                            LLL:EXT:news/Resources/Private/Language/locallang_be.xlf:flexforms_general.topNewsRestriction
                        </label>
                        <config>
                            <type>select</type>
                            <renderType>selectSingle</renderType>
                            <items>
                                <numIndex index="0">
                                    <numIndex index="0">My label</numIndex>
                                    <numIndex index="1">0</numIndex>
                                    <numIndex index="2">my-icon</numIndex>
                                    <numIndex index="3">group1</numIndex>
                                    <numIndex index="4">My Description</numIndex>
                                </numIndex>
                                <numIndex index="1">
                                    <numIndex index="0">My label 1</numIndex>
                                    <numIndex index="1">1</numIndex>
                                    <numIndex index="2">my-icon</numIndex>
                                    <numIndex index="3">group1</numIndex>
                                    <numIndex index="4">My Description</numIndex>
                                </numIndex>
                            </items>
                        </config>
                    </settings.topNewsRestriction>
                </el>
            </ROOT>
        </sDEF>
    </sheets>
</T3DataStructure>
-----
<T3DataStructure>
    <sheets>
        <sDEF>
            <ROOT>
                <sheetTitle>
                    LLL:EXT:news/Resources/Private/Language/locallang_be.xlf:flexforms_tab.settings
                </sheetTitle>
                <type>array</type>
                <el>
                    <settings.topNewsRestriction>
                        <label>
                            LLL:EXT:news/Resources/Private/Language/locallang_be.xlf:flexforms_general.topNewsRestriction
                        </label>
                        <config>
                            <type>select</type>
                            <renderType>selectSingle</renderType>
                            <items>
                                <numIndex index="0">
                                    <label>My label</label>
                                    <value>0</value>
                                    <icon>my-icon</icon>
                                    <group>group1</group>
                                    <description>My Description</description>
                                </numIndex>
                                <numIndex index="1">
                                    <label>My label 1</label>
                                    <value>1</value>
                                    <icon>my-icon</icon>
                                    <group>group1</group>
                                    <description>My Description</description>
                                </numIndex>
                            </items>
                        </config>
                    </settings.topNewsRestriction>
                </el>
            </ROOT>
        </sDEF>
    </sheets>
</T3DataStructure>
