<T3DataStructure>
    <sheets>
        <sDEF>
            <ROOT>
                <sheetTitle>sheetTitle</sheetTitle>
                <type>array</type>
                <el>
                    <settings.radioField>
                        <label>Radio field</label>
                        <config>
                            <type>radio</type>
                            <items>
                                <numIndex index="0">
                                    <numIndex index="0">My label</numIndex>
                                    <numIndex index="1">0</numIndex>
                                </numIndex>
                                <numIndex index="1">
                                    <numIndex index="0">My label 1</numIndex>
                                    <numIndex index="1">1</numIndex>
                                </numIndex>
                                <numIndex index="2">
                                    <numIndex index="0">My label 2</numIndex>
                                    <numIndex index="1">2</numIndex>
                                </numIndex>
                            </items>
                        </config>
                    </settings.radioField>
                </el>
            </ROOT>
        </sDEF>
    </sheets>
</T3DataStructure>
-----
<T3DataStructure>
    <sheets>
        <sDEF>
            <ROOT>
                <sheetTitle>sheetTitle</sheetTitle>
                <type>array</type>
                <el>
                    <settings.radioField>
                        <label>Radio field</label>
                        <config>
                            <type>radio</type>
                            <items>
                                <numIndex index="0">
                                    <label>My label</label>
                                    <value>0</value>
                                </numIndex>
                                <numIndex index="1">
                                    <label>My label 1</label>
                                    <value>1</value>
                                </numIndex>
                                <numIndex index="2">
                                    <label>My label 2</label>
                                    <value>2</value>
                                </numIndex>
                            </items>
                        </config>
                    </settings.radioField>
                </el>
            </ROOT>
        </sDEF>
    </sheets>
</T3DataStructure>
