<T3DataStructure>
    <sheets>
        <sDEF>
            <ROOT>
                <sheetTitle>sheetTitle</sheetTitle>
                <type>array</type>
                <el>
                    <settings.selectField>
                        <label>Select field</label>
                        <config>
                            <type>select</type>
                            <renderType>selectSingle</renderType>
                            <items>
                                <numIndex index="0">
                                    <numIndex index="0">My label</numIndex>
                                    <numIndex index="1">0</numIndex>
                                </numIndex>
                                <numIndex index="1">
                                    <numIndex index="0">My label 1</numIndex>
                                    <numIndex index="1">1</numIndex>
                                </numIndex>
                            </items>
                        </config>
                    </settings.selectField>
                </el>
            </ROOT>
        </sDEF>
    </sheets>
</T3DataStructure>
-----
<T3DataStructure>
    <sheets>
        <sDEF>
            <ROOT>
                <sheetTitle>sheetTitle</sheetTitle>
                <type>array</type>
                <el>
                    <settings.selectField>
                        <label>Select field</label>
                        <config>
                            <type>select</type>
                            <renderType>selectSingle</renderType>
                            <items>
                                <numIndex index="0">
                                    <label>My label</label>
                                    <value>0</value>
                                </numIndex>
                                <numIndex index="1">
                                    <label>My label 1</label>
                                    <value>1</value>
                                </numIndex>
                            </items>
                        </config>
                    </settings.selectField>
                </el>
            </ROOT>
        </sDEF>
    </sheets>
</T3DataStructure>
