<T3DataStructure>
    <sheets>
        <sDEF>
            <ROOT>
                <sheetTitle>sheetTitle</sheetTitle>
                <type>array</type>
                <el>
                    <settings.checkboxField>
                        <label>Checkbox field</label>
                        <config>
                            <type>check</type>
                            <items>
                                <numIndex index="0">
                                    <numIndex index="0">My label</numIndex>
                                    <invertStateDisplay>1</invertStateDisplay>
                                </numIndex>
                            </items>
                        </config>
                    </settings.checkboxField>
                </el>
            </ROOT>
        </sDEF>
    </sheets>
</T3DataStructure>
-----
<T3DataStructure>
    <sheets>
        <sDEF>
            <ROOT>
                <sheetTitle>sheetTitle</sheetTitle>
                <type>array</type>
                <el>
                    <settings.checkboxField>
                        <label>Checkbox field</label>
                        <config>
                            <type>check</type>
                            <items>
                                <numIndex index="0">
                                    <label>My label</label>
                                    <invertStateDisplay>1</invertStateDisplay>
                                </numIndex>
                            </items>
                        </config>
                    </settings.checkboxField>
                </el>
            </ROOT>
        </sDEF>
    </sheets>
</T3DataStructure>
