<?php

\TYPO3\CMS\Extbase\Utility\ExtensionUtility::registerPlugin(
    'TYPO3.CMS.Form',
    'Formframework',
    'Form',
    'content-form'
);

\TYPO3\CMS\Extbase\Utility\ExtensionUtility::registerPlugin(
    'Form',
    'Formframework',
    'Form',
    'content-form'
);

?>
-----
<?php

\TYPO3\CMS\Extbase\Utility\ExtensionUtility::registerPlugin(
    'Form',
    'Formframework',
    'Form',
    'content-form'
);

\TYPO3\CMS\Extbase\Utility\ExtensionUtility::registerPlugin(
    'Form',
    'Formframework',
    'Form',
    'content-form'
);

?>
