imports:
    - { resource: 'services.yaml' }

services:
    Ssch\TYPO3Rector\Rector\Fluid\View\ChangeMethodCallsForStandaloneViewRector: ~
    Ssch\TYPO3Rector\Rector\Core\Utility\RefactorRemovedMethodsFromGeneralUtilityRector: ~
    Ssch\TYPO3Rector\Rector\Frontend\ContentObject\RefactorRemovedMethodsFromContentObjectRendererRector: ~
    Ssch\TYPO3Rector\Rector\Extbase\RemovePropertyUserAuthenticationRector: ~
    Ssch\TYPO3Rector\Rector\Core\TimeTracker\TimeTrackerGlobalsToSingletonRector: ~
    Rector\Renaming\Rector\MethodCall\RenameMethodRector:
        $oldToNewMethodsByClass:
            TYPO3\CMS\Recordlist\RecordList:
                printContent: mainAction
            TYPO3\CMS\Recordlist\Controller\ElementBrowserFramesetController:
                printContent: mainAction
            TYPO3\CMS\Rtehtmlarea\Controller\UserElementsController:
                main: main_user
                printContent: mainAction
            TYPO3\CMS\Rtehtmlarea\Controller\ParseHtmlController:
                main: main_parse_html
                printContent: mainAction
