imports:
    - { resource: 'services.yaml' }

services:
    Ssch\TYPO3Rector\Rector\Fluid\ViewHelpers\MoveRenderArgumentsToInitializeArgumentsMethodRector: ~
    Rector\Php55\Rector\String_\StringClassNameToClassConstantRector: ~
    Ssch\TYPO3Rector\Rector\Annotation\InjectAnnotationRector: ~
    Ssch\TYPO3Rector\Rector\Annotation\IgnoreValidationAnnotationRector: ~

    Ssch\TYPO3Rector\Rector\Annotation\ReplaceAnnotationRector:
        $oldToNewAnnotations:
            # @see https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.0/Feature-83078-ReplaceLazyWithTYPO3CMSExtbaseAnnotationORMLazy.html
            lazy: 'TYPO3\CMS\Extbase\Annotation\ORM\Lazy'

            # @see https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.0/Deprecation-83093-ReplaceCascadeWithTYPO3CMSExtbaseAnnotationORMCascade.html
            cascade: 'TYPO3\CMS\Extbase\Annotation\ORM\Cascade("remove")'

            # @see https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.0/Feature-83092-ReplaceTransientWithTYPO3CMSExtbaseAnnotationORMTransient.html
            transient: 'TYPO3\CMS\Extbase\Annotation\ORM\Transient'

    Ssch\TYPO3Rector\Rector\Annotation\ValidateAnnotationRector: ~
    Ssch\TYPO3Rector\Rector\Core\Environment\ConstantToEnvironmentCallRector: ~
    Ssch\TYPO3Rector\Rector\Core\Package\UsePackageManagerActivePackagesRector: ~
    Ssch\TYPO3Rector\Rector\Core\Environment\RenameMethodCallToEnvironmentMethodCallRector: ~
    Rector\Renaming\Rector\MethodCall\RenameMethodRector:
        $oldToNewMethodsByClass:
            TYPO3\CMS\Core\Resource\ResourceStorage:
                dumpFileContents: streamFile
    Ssch\TYPO3Rector\Rector\Extbase\RemoveFlushCachesRector:
    Ssch\TYPO3Rector\Rector\Extbase\RemoveInternalAnnotationRector:
    Ssch\TYPO3Rector\Rector\Migrations\RenameClassMapAliasRector:
        $classAliasMaps:
            - '../../../Migrations/Fluid/ClassAliasMap.php'
    Ssch\TYPO3Rector\Rector\Extbase\ConfigurationManagerAddControllerConfigurationMethodRector: ~
    Ssch\TYPO3Rector\Rector\Frontend\Page\RemoveInitMethodFromPageRepositoryRector: ~
