<?php

use TYPO3\CMS\Core\Imaging\Icon;

$icon1 = Icon::SIZE_DEFAULT;
$icon2 = Icon::SIZE_SMALL;
$icon3 = Icon::SIZE_MEDIUM;
$icon4 = Icon::SIZE_LARGE;
$icon5 = Icon::SIZE_MEGA;

?>
-----
<?php

use TYPO3\CMS\Core\Imaging\IconSize;
use TYPO3\CMS\Core\Imaging\Icon;

$icon1 = IconSize::DEFAULT;
$icon2 = IconSize::SMALL;
$icon3 = IconSize::MEDIUM;
$icon4 = IconSize::LARGE;
$icon5 = IconSize::MEGA;

?>
