name: Coding Standard

on:
    pull_request: null
    push:
        branches:
            - "main"

env:
    # see https://github.com/composer/composer/issues/9368#issuecomment-718112361
    COMPOSER_ROOT_VERSION: "dev-main"

jobs:
    coding_standard:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2.0.0

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.0
                    coverage: none
                env:
                    COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            # see https://github.com/ramsey/composer-install
            -   uses: "ramsey/composer-install@v1"

            -   run: vendor/bin/ecs check --fix

            -   uses: stefanzweifel/git-auto-commit-action@v4.12.0
                with:
                    commit_message: Apply coding standard changes
                    branch: "main"
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
