services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TYPO3\CMS\FrontendLogin\:
    resource: '../Classes/*'

  TYPO3\CMS\FrontendLogin\Event\ProcessRequestTokenListener:
    tags:
      - name: event.listener
        identifier: felogin-process-request-token
